### ISSUE TITLE
The Sample works fine with Work or School Account. WHat goes wrong with personal account

### ISSUE THREAD

**Issue by gerritjb** [microsoftgraph/aspnetcore-connect-sample#12] opened 2018-04-04 06:54 UTC
When singing in with personal account, and then want to send a mail I get the error page. Even in development mode I don't the more debug info on what goes wrong.
Why do I get the /home/error page instead of the Development Error handler. And why can I not send mail with the sample from a personal account?

**Comment by mark-szabo** [comment] 2018-04-04 07:01
Thanks for the feedback gerritjb! Will look into this soon. It can be that the email sending endpoint does not support MSA. Or only the v2.0 endpoint supports it.

**Comment by mark-szabo** [comment] 2018-04-07 18:26
Yes, the problem is with the endpoint as I thought. When sending an email the user profile picture is attached. Therefore it is needed to be downloaded from Graph first, but it will throw an error saying operation is not supported as getting user picture with an MSA account is only supported with the v2.0 endpoint. Working on a fix now.

**Comment by mark-szabo** [comment] 2018-04-07 18:31
Issue should be solved. Let me know if it's working for you and we can close the issue! :)

**Comment by gerritjb** [comment] 2018-04-08 04:59
Issue can be closed ;-) Your answer helpt me where to look. ThankS!

**Comment by mark-szabo** [comment] 2018-04-08 09:09
Great, check out the commit linked above (a9a7fea) with my fix if you need help with the implementation :)

**Closed as completed by mark-szabo** 2018-04-08 09:09 UTC
Labels: bug: sample, fixed

**Comment by gerritjb** [comment] 2018-04-08 09:46
Nice! With the conditional beta endpoint!




________________________________
