### ISSUE TITLE
Single tenant - Guest Account login error - Null Token

### ISSUE THREAD

**Issue by anujabhojani** [microsoftgraph/aspnetcore-connect-sample#62] opened 2020-06-15 12:47 UTC
1. Updated the GraphAuthProvider.cs for supporting single tenant.
 _app = ConfidentialClientApplicationBuilder.Create(azureOptions.ClientId)
                    .WithClientSecret(azureOptions.ClientSecret)
                    .WithTenantId(azureOptions.TenantId)
                    .WithAuthority(AzureCloudInstance.AzurePublic, AadAuthorityAudience.AzureAdMyOrg)
                    .WithRedirectUri(azureOptions.BaseUrl + azureOptions.CallbackPath)
                    .Build();
Azure App updated for Single Tenant:
![image](https://user-images.githubusercontent.com/3500375/84658854-dc3a9b80-af59-11ea-864a-34ab6c4cd877.png)

2. From Azure Portal, Invited the Guest User. 
![image](https://user-images.githubusercontent.com/3500375/84657478-b0b6b180-af57-11ea-9905-aaa866327fa4.png)
3. Tried to login with Guest account,  login url goes into loop.
Debugging shows that getting the null in
var account = await _app.GetAccountAsync(userId); 

![image](https://user-images.githubusercontent.com/3500375/84658453-47d03900-af59-11ea-815b-48cf0cef664b.png)

![image](https://user-images.githubusercontent.com/3500375/84658579-70f0c980-af59-11ea-8e9d-b27ef22dd8c8.png)

Any help to solve this issue?

**Comment by mark-szabo** [comment] 2020-07-16 12:09
I was able to repro the issue. The problem is, that the guest user's token is cached, but the identifier consists of the guest user's original oid and tenant id. In contrast, when we are getting the account, we are trying to do that with the guest tenant's tenant id and the guest oid of the guest user (users get new oids when they join an external AD). And that's why `account` is null.

@jmprieur do you have any info about this? How should this case be handled?

**Comment by jasonjoh** [comment] 2023-04-12 13:14
Closing issue as we are archiving this repository.

**Closed as completed by jasonjoh** 2023-04-12 13:14 UTC
Labels: bug, area: authentication
